import sl from "./generated/sl-skeleton.json" with { type: "json" };
import { Skeleton } from "./skeleton.ts";
import type { SkeletonData, Vec3 } from "./types.ts";

/** The Second Life avatar skeleton (Bento-era, 133 joints + 26 collision volumes) as generated by `tools/import-sl-skeleton`. */
export const SL_SKELETON_DATA = sl as unknown as SkeletonData;

export const createSlSkeleton = (): Skeleton => new Skeleton(SL_SKELETON_DATA);

/**
 * Basis change from SL space (+X forward, +Y left, +Z up) to the viewport's three.js space
 * (+Z forward, +X avatar-left, +Y up): three = (sl.y, sl.z, sl.x). A proper rotation (det +1).
 * Column-major 4x4.
 */
export const SL_TO_THREE: readonly number[] = [
  0, 0, 1, 0,
  1, 0, 0, 0,
  0, 1, 0, 0,
  0, 0, 0, 1,
];

export const slToThree = (v: Vec3): Vec3 => [v[1], v[2], v[0]];
